// This file is auto-generated by @hey-api/openapi-ts

export type GetMoonData = {
    query: {
        /**
         * date (on YYYY-MM-DD format) in local time, not UTC. Defaults to today
         */
        date?: string;
        /**
         * latitude
         */
        lat: number;
        /**
         * longtitude
         */
        lon: number;
        /**
         * timezone offset string (e.g +02:00 or -04:30")
         */
        offset?: string;
    };
};

export type GetMoonResponse = string | void;

export type GetMoonError = unknown;

export type GetSunData = {
    query: {
        /**
         * date (on YYYY-MM-DD format) in local time, not UTC. Defaults to today
         */
        date?: string;
        /**
         * latitude
         */
        lat: number;
        /**
         * longtitude
         */
        lon: number;
        /**
         * timezone offset string (e.g +02:00 or -04:30")
         */
        offset?: string;
    };
};

export type GetSunResponse = string | void;

export type GetSunError = unknown;

export type GetChangelogResponse = unknown;

export type GetChangelogError = unknown;

export type GetHealthzResponse = unknown;

export type GetHealthzError = unknown;

export type GetValuesData = {
    query?: {
        param?: "type";
    };
};

export type GetValuesResponse = unknown;

export type GetValuesError = unknown;
